addEvent( "resyncMyWeapon", true )
addEventHandler( "resyncMyWeapon", resourceRoot, function(weapon)
	--outputDebugString(getPlayerName(client)  .. "'s weapon resynced. (" .. getWeaponNameFromID(weapon) .. ")")
	giveWeapon(client, weapon, 0, true)
end )